manifest:
  remotes:
    - name: timstewartj
      url-base: https://github.com/timstewartj
  projects:
    - name: zmk-firmware
      remote: timstewartj
      revision: caksoylar/zen-v1+v2  # custom branch name
      import: app/west.yml
  self:
    path: config
